#!/bin/sh

# Run LinWarrior
#./dist/linwarrior game -r 320 -m 0
#./dist/linwarrior game -r 640 -m 0 -w -l 0
#./dist/linwarrior game -r 800 -m 0 -w -l 0
#./dist/linwarrior game -r 1024 -m 0 -s 4
#./dist/linwarrior game -r 1280 -m 0 -l 1
#./dist/linwarrior game -r 1280 -m 0 -l 0 -w
./dist/linwarrior game -r 1680x1050 -m 0 -s 0 -l 1
# 20:9
#./dist/linwarrior game -r 1680x756 -m 0 -s 0 -l 1

